spring.application.name=ReviseSpringBoot

spring.datasource.url=jdbc:postgresql://localhost:5432/studentDB
spring.datasource.username=postgres
spring.datasource.password=PtgSQL@12345

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show.sql= true
spring.jpa.properties.hibernate.formate_sql = true